<a href="https://colab.research.google.com/github/rranjithkumar100/AI-Training/blob/main/Day20_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

# scalar - not suitable for data process
my1DArray = np.array([1,2,3,4,5])
print(my1DArray)
print("Dimension: "+ str(my1DArray.ndim))

[1 2 3 4 5]
Dimension: 1


In [11]:
# vector - 2 dimension
my2DArray = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(my2DArray)
print("Dimension: "+ str(my2DArray.ndim))

[[1 2 3 4 5]
 [1 2 3 4 5]]
Dimension: 2


In [13]:
my3DArray = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])
print(my3DArray)
print("Dimension: "+ str(my3DArray.ndim))

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]
Dimension: 3


In [16]:
# arrange function

print(np.arange(10)) # zero to 10
print(np.arange(1,10)) # start to end (1 to 10)
print(np.arange(1,100,5)) # start to end with step (1 to 100 increase 5 by 5)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [17]:
# line space random number

a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [18]:
b = np.linspace(1,10,5)
print(b)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
c = np.linspace(1,10,20)
print(c)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [20]:
# random int with 4*4 matrix
d = np.random.randint(1,10,(4,4))
print(d)

[[3 6 9 9]
 [1 8 6 5]
 [7 7 5 5]
 [2 4 1 8]]


In [21]:
e = np.random.randint(1000, size=(4,4), dtype = np.int16)
print(e)

[[173 227 285 817]
 [ 41 222 935 458]
 [360 312 931 692]
 [648 284 909 136]]


In [24]:
f = np.random.randint(1000,2000, 30)
print(f)

[1491 1764 1874 1789 1099 1388 1603 1351 1078 1578 1889 1932 1613 1705
 1652 1629 1030 1738 1277 1656 1932 1329 1230 1122 1788 1081 1601 1168
 1941 1773]


In [26]:
# slicing the 2d data

my2dArray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my2dArray)

my2dArray[0:2,0:2]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[1, 2],
       [6, 7]])

In [27]:
# slicing 3d array

my3dArray = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(my3dArray)

my3dArray[0:2,0:2,0:2]

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


array([[[ 1,  2],
        [ 6,  7]],

       [[11, 12],
        [16, 17]]])

In [33]:
# empty array

emptyArray = np.empty((3,2),dtype = np.int32)
print(emptyArray)

[[         0          0]
 [         0 1071644672]
 [         0 1072693248]]
