<a href="https://colab.research.google.com/github/rranjithkumar100/AI-Training/blob/main/Day_41_Simple_Linear_Regression_With_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([i for i in range(1,11)])

In [3]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
y = np.array([i*7 for i in range(1,11)])

In [5]:
y

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [6]:
x = x.reshape(-1,1)

In [7]:
from keras.models import Sequential
from keras.layers import Dense

In [8]:
model = Sequential()

In [9]:
model.add(Dense(units=1, input_shape=(1,), activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.compile(optimizer='sgd', loss='mse')

In [20]:
model.fit(x,y,epochs=124)

Epoch 1/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.0222
Epoch 2/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0220
Epoch 3/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0218
Epoch 4/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0217
Epoch 5/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0215
Epoch 6/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0213
Epoch 7/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0211
Epoch 8/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0209
Epoch 9/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0208
Epoch 10/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0206
Epoch 11/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0204
Epoch 12/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0203
Epoch 13/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0201
Epoch 14/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0199
Epoch 15/124
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0197
Epoch 16/124
1/1 ━━

In [21]:
prediction = model.predict(np.array([12]).reshape(-1,1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


In [22]:
prediction

array([[83.86173]], dtype=float32)